

DEFAULT_MODE = 1
DEFAULT_SIMPLE_THRESHOLD = 100
DEFAULT_SCALE = 2.5
DEFAULT_PSM = 7
IS_CLAHE_ENABLED = True
IS_MORPHOLOGY_ENABLED = False

IS_SAVING_ENABLED = False
DEFAULT_SAVE_INTERVAL_SECONDS = 5.0
EXCEL_FILENAME = "measurements.xlsx"

OCR_INTERVAL_SECONDS = 0.2
FPS_CALCULATION_INTERVAL_S = 1.0

